# Generated by Django 4.0.4 on 2022-07-28 07:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0004_remove_contact_date_create_alter_contact_email_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='booking',
            name='item_id',
            field=models.CharField(max_length=200, null=True),
        ),
    ]
