# Generated by Django 4.0.4 on 2022-07-28 10:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0005_alter_booking_item_id'),
    ]

    operations = [
        migrations.CreateModel(
            name='product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('item_name', models.CharField(max_length=200, null=True)),
                ('item_id', models.CharField(max_length=200, null=True)),
                ('des', models.CharField(max_length=200, null=True)),
                ('price', models.CharField(max_length=20, null=True)),
            ],
        ),
    ]
